/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrivateRouteImport } from './routes/_private'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as PrivateSlugRouteImport } from './routes/_private/$slug'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as PublicSignUpRouteImport } from './routes/_public/sign-up'
import { Route as PrivateSlugAppointmentsRouteImport } from './routes/_private/$slug.appointments'
import { Route as PrivateSlugDashboardRouteImport } from './routes/_private/$slug.dashboard'
import { Route as PrivateSlugPatientsRouteImport } from './routes/_private/$slug.patients'
import { Route as PrivateSlugSettingsRouteImport } from './routes/_private/$slug.settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateRoute = PrivateRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateSlugRoute = PrivateSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PrivateRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSignUpRoute = PublicSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => PublicRoute,
} as any)
const PrivateSlugAppointmentsRoute = PrivateSlugAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => PrivateSlugRoute,
} as any)
const PrivateSlugDashboardRoute = PrivateSlugDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PrivateSlugRoute,
} as any)
const PrivateSlugPatientsRoute = PrivateSlugPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => PrivateSlugRoute,
} as any)
const PrivateSlugSettingsRoute = PrivateSlugSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PrivateSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof PrivateSlugRouteWithChildren
  '/login': typeof PublicLoginRoute
  '/sign-up': typeof PublicSignUpRoute
  '/$slug/appointments': typeof PrivateSlugAppointmentsRoute
  '/$slug/dashboard': typeof PrivateSlugDashboardRoute
  '/$slug/patients': typeof PrivateSlugPatientsRoute
  '/$slug/settings': typeof PrivateSlugSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof PrivateSlugRouteWithChildren
  '/login': typeof PublicLoginRoute
  '/sign-up': typeof PublicSignUpRoute
  '/$slug/appointments': typeof PrivateSlugAppointmentsRoute
  '/$slug/dashboard': typeof PrivateSlugDashboardRoute
  '/$slug/patients': typeof PrivateSlugPatientsRoute
  '/$slug/settings': typeof PrivateSlugSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_private': typeof PrivateRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_private/$slug': typeof PrivateSlugRouteWithChildren
  '/_public/login': typeof PublicLoginRoute
  '/_public/sign-up': typeof PublicSignUpRoute
  '/_private/$slug/appointments': typeof PrivateSlugAppointmentsRoute
  '/_private/$slug/dashboard': typeof PrivateSlugDashboardRoute
  '/_private/$slug/patients': typeof PrivateSlugPatientsRoute
  '/_private/$slug/settings': typeof PrivateSlugSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/login'
    | '/sign-up'
    | '/$slug/appointments'
    | '/$slug/dashboard'
    | '/$slug/patients'
    | '/$slug/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/login'
    | '/sign-up'
    | '/$slug/appointments'
    | '/$slug/dashboard'
    | '/$slug/patients'
    | '/$slug/settings'
  id:
    | '__root__'
    | '/'
    | '/_private'
    | '/_public'
    | '/_private/$slug'
    | '/_public/login'
    | '/_public/sign-up'
    | '/_private/$slug/appointments'
    | '/_private/$slug/dashboard'
    | '/_private/$slug/patients'
    | '/_private/$slug/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivateRoute: typeof PrivateRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PrivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/$slug': {
      id: '/_private/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof PrivateSlugRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/sign-up': {
      id: '/_public/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof PublicSignUpRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_private/$slug/appointments': {
      id: '/_private/$slug/appointments'
      path: '/appointments'
      fullPath: '/$slug/appointments'
      preLoaderRoute: typeof PrivateSlugAppointmentsRouteImport
      parentRoute: typeof PrivateSlugRoute
    }
    '/_private/$slug/dashboard': {
      id: '/_private/$slug/dashboard'
      path: '/dashboard'
      fullPath: '/$slug/dashboard'
      preLoaderRoute: typeof PrivateSlugDashboardRouteImport
      parentRoute: typeof PrivateSlugRoute
    }
    '/_private/$slug/patients': {
      id: '/_private/$slug/patients'
      path: '/patients'
      fullPath: '/$slug/patients'
      preLoaderRoute: typeof PrivateSlugPatientsRouteImport
      parentRoute: typeof PrivateSlugRoute
    }
    '/_private/$slug/settings': {
      id: '/_private/$slug/settings'
      path: '/settings'
      fullPath: '/$slug/settings'
      preLoaderRoute: typeof PrivateSlugSettingsRouteImport
      parentRoute: typeof PrivateSlugRoute
    }
  }
}

interface PrivateSlugRouteChildren {
  PrivateSlugAppointmentsRoute: typeof PrivateSlugAppointmentsRoute
  PrivateSlugDashboardRoute: typeof PrivateSlugDashboardRoute
  PrivateSlugPatientsRoute: typeof PrivateSlugPatientsRoute
  PrivateSlugSettingsRoute: typeof PrivateSlugSettingsRoute
}

const PrivateSlugRouteChildren: PrivateSlugRouteChildren = {
  PrivateSlugAppointmentsRoute: PrivateSlugAppointmentsRoute,
  PrivateSlugDashboardRoute: PrivateSlugDashboardRoute,
  PrivateSlugPatientsRoute: PrivateSlugPatientsRoute,
  PrivateSlugSettingsRoute: PrivateSlugSettingsRoute,
}

const PrivateSlugRouteWithChildren = PrivateSlugRoute._addFileChildren(
  PrivateSlugRouteChildren,
)

interface PrivateRouteChildren {
  PrivateSlugRoute: typeof PrivateSlugRouteWithChildren
}

const PrivateRouteChildren: PrivateRouteChildren = {
  PrivateSlugRoute: PrivateSlugRouteWithChildren,
}

const PrivateRouteWithChildren =
  PrivateRoute._addFileChildren(PrivateRouteChildren)

interface PublicRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute
  PublicSignUpRoute: typeof PublicSignUpRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
  PublicSignUpRoute: PublicSignUpRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivateRoute: PrivateRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
