/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrivateRouteImport } from './routes/_private'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as PrivateAppointmentsRouteImport } from './routes/_private/appointments'
import { Route as PrivateDashboardRouteImport } from './routes/_private/dashboard'
import { Route as PrivatePatientsRouteImport } from './routes/_private/patients'
import { Route as PrivateSettingsRouteImport } from './routes/_private/settings'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as PublicSignUpRouteImport } from './routes/_public/sign-up'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateRoute = PrivateRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateAppointmentsRoute = PrivateAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateDashboardRoute = PrivateDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivatePatientsRoute = PrivatePatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateSettingsRoute = PrivateSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PrivateRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSignUpRoute = PublicSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => PublicRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/appointments': typeof PrivateAppointmentsRoute
  '/dashboard': typeof PrivateDashboardRoute
  '/patients': typeof PrivatePatientsRoute
  '/settings': typeof PrivateSettingsRoute
  '/login': typeof PublicLoginRoute
  '/sign-up': typeof PublicSignUpRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/appointments': typeof PrivateAppointmentsRoute
  '/dashboard': typeof PrivateDashboardRoute
  '/patients': typeof PrivatePatientsRoute
  '/settings': typeof PrivateSettingsRoute
  '/login': typeof PublicLoginRoute
  '/sign-up': typeof PublicSignUpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_private': typeof PrivateRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_private/appointments': typeof PrivateAppointmentsRoute
  '/_private/dashboard': typeof PrivateDashboardRoute
  '/_private/patients': typeof PrivatePatientsRoute
  '/_private/settings': typeof PrivateSettingsRoute
  '/_public/login': typeof PublicLoginRoute
  '/_public/sign-up': typeof PublicSignUpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/appointments'
    | '/dashboard'
    | '/patients'
    | '/settings'
    | '/login'
    | '/sign-up'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/appointments'
    | '/dashboard'
    | '/patients'
    | '/settings'
    | '/login'
    | '/sign-up'
  id:
    | '__root__'
    | '/'
    | '/_private'
    | '/_public'
    | '/_private/appointments'
    | '/_private/dashboard'
    | '/_private/patients'
    | '/_private/settings'
    | '/_public/login'
    | '/_public/sign-up'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivateRoute: typeof PrivateRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PrivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/appointments': {
      id: '/_private/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof PrivateAppointmentsRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/dashboard': {
      id: '/_private/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof PrivateDashboardRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/patients': {
      id: '/_private/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof PrivatePatientsRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/settings': {
      id: '/_private/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof PrivateSettingsRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/sign-up': {
      id: '/_public/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof PublicSignUpRouteImport
      parentRoute: typeof PublicRoute
    }
  }
}

interface PrivateRouteChildren {
  PrivateAppointmentsRoute: typeof PrivateAppointmentsRoute
  PrivateDashboardRoute: typeof PrivateDashboardRoute
  PrivatePatientsRoute: typeof PrivatePatientsRoute
  PrivateSettingsRoute: typeof PrivateSettingsRoute
}

const PrivateRouteChildren: PrivateRouteChildren = {
  PrivateAppointmentsRoute: PrivateAppointmentsRoute,
  PrivateDashboardRoute: PrivateDashboardRoute,
  PrivatePatientsRoute: PrivatePatientsRoute,
  PrivateSettingsRoute: PrivateSettingsRoute,
}

const PrivateRouteWithChildren =
  PrivateRoute._addFileChildren(PrivateRouteChildren)

interface PublicRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute
  PublicSignUpRoute: typeof PublicSignUpRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
  PublicSignUpRoute: PublicSignUpRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivateRoute: PrivateRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
